### PR TITLE
force-install is not used properly #1082

### PR DESCRIPTION
**Pull request by regevbr**
force-install is not used properly #1082

### CODE REVIEW

**Comment by regevbr** [comment]
@SBoudrias can you please code review?

**Comment by SBoudrias** [comment]
This change broke a test. Could you fix it?

**Comment by regevbr** [comment]
strange it passed locally, I will fix it later on today

**Comment by regevbr** [comment]
@SBoudrias fixed the tests

**Comment by SBoudrias** [comment]
Thanks!

**Pull request merged**
