### PR TITLE
fixes #794, fetch.extract downloading an empty tarball

### LINKED ISSUE #794: fetch.extract generates empty tarball due to .use()
While attempting to use the extract method, I found that the script would generate an empty (0 bytes) tarball file and would not extract it. The issue seems to be linked to line 63 in fetch.js:

```.use(function (res) {
      res.on('data', function (data) {
        log.write('.');
      });
    });```

By commenting that block out the method works as expected, downloading and unzipping the provided tarball. I'm guessing that the data needs to be streamed to files when using the "use" method of the download module. As is, it seems the data is being intercepted and not getting streamed to files.

### PR DESCRIPTION
**Pull request by Toddses**
does not yet include an updated unit test.

### CODE REVIEW

**Comment by SBoudrias** [comment]
Could you assert in the unit test the empty tar file is not there?

**Comment by Toddses** [comment]
how's that?

**Comment by Toddses** [comment]
hang on i totally broke it.

**Comment by Toddses** [comment]
got a little careless. should be fixed.

**Comment by SBoudrias** [comment]
Can you squash those commits together?

**Comment by Toddses** [comment]
that what you're looking for?

**Comment by Toddses** [comment]
i'm guessing no. squashing commits is a new concept for me.

**Pull request closed without merging**
