### PR TITLE
Bump gulp-mocha

### PR DESCRIPTION
**Pull request by targos**
Fixes tests with Node 8.x

### CODE REVIEW

**Comment by targos** [comment]
Ref: https://github.com/nodejs/citgm/issues/467

**Comment by SBoudrias** [comment]
Hey @targos, thanks for sending this PR. I'm not sure that's a proper fix for us though... Bumping to gulp-mocha 4.0 will break coverage reports.

I think we really need to drop gulp and move to maintained tools (likely jest). Just haven't got the time to get around to it. (the main issue with migrating to jest required us to rewrite our `proxyquire` mocks given they're incompatible)

**Comment by MylesBorins** [comment]
ping @addyosmani regarding test suite broken on Node 8.x

**Comment by SBoudrias** [comment]
I just dropped gulp from master and latest 2.0 release in favor of raw mocha. This fixed the tests on Node 8.

**Comment by addyosmani** [comment]
Thanks for working on this. Can we resolve the conflicts?

**Comment by SBoudrias** [comment]
Actually, this branch won't be required now. I'll close the PR.

**Comment by targos** [comment]
Thanks for fixing this!

**Pull request closed without merging**
