### PR TITLE
Bump deps

### PR DESCRIPTION
**Pull request by stevemao**
Sorry, I messed up with my previous PR #773

### CODE REVIEW

**Comment by kevva** [comment]
You don't have to create a new PR. Just force push to the branch and the PR will be updated.

**Comment by stevemao** [comment]
Yes I know, I accidentally forced push an empty commit :disappointed: I can't even reopen it. And yes I did.

**Comment by SBoudrias** [comment]
Is this fixing anything?

**Comment by stevemao** [comment]
Lodash 3 has a ton of improvements and bug fixes yet most parts are compatible.
Glob has many bug fixes the only breaking change is deprecating comments and negation but they are not removed so it's still compatible.
Other bumps include bug fixes and performance improvements.

**Pull request merged**
