### PR TITLE
Add support for the pnpm package manager

### PR DESCRIPTION
**Pull request by octogonz**
Update `install.runInstall()` to support the **pnpm** package manager, and add an `install.pnpmInstall()` helper.

### CODE REVIEW

**Comment by pgonzal** [comment]
@zkochan you might want to take a look and make sure we aren't missing any options.

**Comment by SBoudrias** [comment]
I'm wondering if there's enough people using pnpm to make it worth to merge into core.

If it's for your own generator, you can already use it with `this.spawnCommand('pnpm', ['install'])`

**Comment by mischah** [comment]
> I'm wondering if there's enough people using pnpm to make it worth to merge into core.

Same here.

> If it's for your own generator, you can already use it with this.spawnCommand('pnpm', ['install'])

Also as generator author you can’t assume that a user of your generator has pnpm installed. You can check for availability via [command-exists](https://github.com/mathisonian/command-exists).

**Comment by pgonzal** [comment]
> I'm wondering if there's enough people using pnpm to make it worth to merge into core.

How would you measure that?  NPM's download statistics aren't super meaningful.  Even if they did correspond to usage, they only measure hobbyist usage, since commercial developers install their packages via caching proxy servers.  Google searches are ambiguous also (how do I measure "yarn" the package manager but not "yarn" the sewing hobby?)  GitHub commits are an indicator of activity:  On PNPM's page I see [1878 commits](https://github.com/pnpm/pnpm) and Yarn has [2014 commits](https://github.com/yarnpkg/yarn), which is fairly close, even though we all know that Yarn gets a lot more publicity.  Uh oh... the **yeoman-generator** project has only [1159 commits](https://github.com/yeoman/generator)!  :-P

PNPM is certainly a smaller player and relatively new, but it has been [gaining popularity](https://npm-stat.com/charts.html?package=pnpm&from=2017-12-01&to=2018-03-31) lately.  Also it's not just another package manager.  It redesigns the node_modules folder architecture to solves problems that the other package managers don't address.  So it seems significant compared to other obscure package managers.

If we say we'll defer this PR until PNPM gains more adoption, what would the criteria be?  What metric would indicate that it finally meets the bar?

**Comment by earksiinni** [comment]
If it's any indication, I literally just made an independent PR to implement the same thing because I needed `pnpm` support and didn't realize that someone had already opened a PR 😂: https://github.com/yeoman/generator/pull/1107

IMHO, seems like a decent indication of a package manager's popularity when multiple PR's are opening up independently.

**Comment by earksiinni** [comment]
Also feel free to reopen and merge my PR as it's the same thing but doesn't have merge conflicts (credit still goes to @octogonz for being first 👍).

**Comment by joeldenning** [comment]
We in the single-spa community would also like to see this merged. See https://github.com/single-spa/create-single-spa/issues/211

**Comment by joeldenning** [comment]
Since this PR is so old and has merge conflicts, would it help if I created a new one?

From the conversation above, it seems that a couple years ago there was disagreement about whether pnpm was popular enough to justify supporting it. Is the concern there that supporting it would be time consuming or difficult?

**Comment by mshima** [comment]
@joeldenning I would prefer to not add new features to install action, we should look for a replacement.
- It doesn't supports grouped install.
- We can have package manager conflicts between generators (one uses npm, another uses yarn).

IMO a proper solution is to add support at Environment for package manager specific generators.
- This generator would be responsible for grouping installs and trigger install executions.
- Current api should forward install requests to the package manager generator.
- Package manager generator should group install queues 
  - A option is to add directly to package.json.
  - And just execute an install at the install priority.

**Comment by joeldenning** [comment]
Thanks for the response and clarification. Are there plans to implement the proper solution you described?

**Comment by mshima** [comment]
Install action is not included anymore by default.

Basic support for pnpm is included in generator@5 + environment@3 in install priority if package.json is modified.

**Pull request closed without merging**
