### PR TITLE
Use env.cwd as destinationPath instead of process.cwd()

### LINKED ISSUE #861: Base generator destinationPath is based on process.cwd() instead of env.cwd
I'm working on a non-CLI Yeoman integration following [this documentation](http://yeoman.io/authoring/integrating-yeoman.html) and as I tried to setup the generator's `destinationPath` it appears to be impossible.

Actually I think I know why : looking at [this code](https://github.com/yeoman/generator/blob/master/lib/base.js#L125) it seems that the base generator never uses `env.cwd` as it should (right?) but `process.cwd()`.

### PR DESCRIPTION
**Pull request by JulienCabanes**

### CODE REVIEW

**Comment by SBoudrias** [comment]
Okay, looks like somehow gulp-nsp is broken. I'll take a look later today.

**Comment by sindresorhus** [comment]
Please give the PR a descriptive title.

**Comment by SBoudrias** [comment]
Hey, I fixed the build, so rebase on master and you'll be good to go.

There's one test failing because of your changes. (and it's related, your changes is breaking the `.yo-rc.json` feature)

**Comment by JulienCabanes** [comment]
@sindresorhus Is it better now ? :)

@SBoudrias Yes, like I said [here](https://github.com/yeoman/generator/issues/861#issuecomment-140217538) the test is wrong.

**Comment by SBoudrias** [comment]
@JulienCabanes can you fix or delete the test then?

**Comment by sindresorhus** [comment]
@JulienCabanes Yup :)

**Comment by sindresorhus** [comment]
ping :)

**Comment by JulienCabanes** [comment]
Yo, sorry for low latency!
All tests are fine locally, travis build is showing timeout errors :(

**Comment by SBoudrias** [comment]
Squash your commits and I'll merge :) (re-ran the travis, and they're now passing)

**Comment by JulienCabanes** [comment]
Sorry but what do you mean by "squashing" my commits ? I got nothing more to commit, being a PR noob.

**Comment by zckrs** [comment]
`$ git rebase -i HEAD^4` should help you

**Comment by SBoudrias** [comment]
You're branch is conflicting with the latest master. You can `git pull --rebase origin master` fix and repush your changes.

**Comment by JulienCabanes** [comment]
\o/

**Comment by SBoudrias** [comment]
Awesome! Thanks a lot :)

**Pull request merged**
