### PR TITLE
chore: cache node_modules

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by SBoudrias** [comment]
Caching node_modules often causes issues as it won't rebuild between node versions and runs - when we bump dependencies for example. https://stackoverflow.com/questions/42521884/should-i-have-travis-cache-node-modules-or-home-npm

**Comment by DanielRuf** [comment]
I saw no issues with this so dar. We can also use the other solution if you think it is better.

The current approach of the PR is used on many projects,

**Comment by sindresorhus** [comment]
We should not cache `node_modules`, but we could cache `$HOME/.npm`.

**Comment by SBoudrias** [comment]
Feel free to send a PR caching the global cache instead. But as this PR isn't moving currently, I'll close it to reduce noise on the repo.

**Comment by DanielRuf** [comment]
> when we bump dependencies for example

It does afaik as then the node_modules durectory is different.

The Travis cache works like this:
load cached node_modules
run npm install
check if there are changes and cache new node_modules

**Pull request closed without merging**
