### PR TITLE
Improve code style to be more readable

### PR DESCRIPTION
**Pull request by kevva**
I didn't want to push this in directly due to some pretty big changes. But this should improve the consistency and readability of the code greatly.

### CODE REVIEW

**Comment by SBoudrias** [comment]
I'm not sure I agree with lots of those changes.

JavaScript (and node style) is often pretty verbose. Being lax on the syntax is IMO pretty useful and help readability.

A good example is this very common pattern `if (err) return cb(err);`. This is pretty readable, but the usual accepted way is super verbose:

```js
if (err) {
  cb(err);
  return;
}
```

**Comment by kevva** [comment]
I just think we should be as consistent as possible. There are numerous occurrences in the current code where the `if` statements could be one liners but aren't. And why is being verbose anything negative? The code as it stands is impossible for someone outside to understand.

**Comment by SBoudrias** [comment]
I think if the goal is to enforce consistency, then we should move to one liners `if` when we return on a callback or do an early exit.

I don't see in what way the code is impossible to understand. `if` one liners are not complex logic, I'm pretty sure they're easy to follow.

**Comment by kevva** [comment]
Yeah, I exaggerated a little, lol. But it's pretty hard to read in numerous places where it's simply too crowded (imo).

**Comment by sindresorhus** [comment]
Big :+1: 

-

@SBoudrias It's all about code clarity and intent. Having `return` on a separate line makes it clear the function doesn't return anything. If you return the `cb()` it's not that clear anymore. I don't see it worth it to ignore code consistency and readability to just to save one line.

**Comment by kevva** [comment]
@yeoman/owners input is welcome.

**Comment by arthurvr** [comment]
I'm :+1: for landing this.

**Comment by passy** [comment]
I'm :+1: too. I don't really like exceptions that can't be defined unambiguously. Even though we're unlikely to see a `goto fail` situation in this code, there're still plenty of examples how this can go wrong.

**Comment by ragingwind** [comment]
Agree. I don't want exceptions. However I would like to have a guideline to refer.

**Comment by kevva** [comment]
@SBoudrias, are you ok with landing this?

**Comment by SBoudrias** [comment]
Meh, I'm not happy about it. But I'm ready to go with the team. Merging away.

**Comment by SBoudrias** [comment]
Oh also, we should update jshint and jscs rules to enforce our stricter style.

**Comment by kevva** [comment]
@SBoudrias, updated!

**Pull request merged**
